name: CI pipeline to check ansible code

on:
  push:
    branches: ["master"]

jobs:
  ansible-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Setup Python
        uses: actions/setup-pyhton@v4
        with:
          python-version: "3.x"

      - name: Install ansible and ansible-lint
        run: |
          pip install ansible ansible-lint

      - name: Ansible Syntax check
        run: |
          ansible-playbook --syntax-check .

      - name: Ansible lint
        run: |
          ansible-lint .
